# Generated by Django 2.2.1 on 2019-06-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_book_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=25)),
                ('comment', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('for_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Book')),
            ],
        ),
    ]
