# Generated by Django 2.2.1 on 2019-07-09 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
